/*
 * FinTech api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentapiFx struct {
	ContractReference string `json:"contract_reference,omitempty"`
	ExchangeRate string `json:"exchange_rate,omitempty"`
	OriginalAmount string `json:"original_amount,omitempty"`
	OriginalCurrency string `json:"original_currency,omitempty"`
}
