/*
 * FinTech api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentapiPaymentAttributes struct {
	Amount string `json:"amount,omitempty"`
	Currency string `json:"currency,omitempty"`
	NumericReference string `json:"numeric_reference,omitempty"`
	PaymentId string `json:"payment_id,omitempty"`
	PaymentPurpose string `json:"payment_purpose,omitempty"`
	PaymentScheme string `json:"payment_scheme,omitempty"`
	PaymentType string `json:"payment_type,omitempty"`
	ProcessingDate string `json:"processing_date,omitempty"`
	Reference string `json:"reference,omitempty"`
	SchemePaymentSubType string `json:"scheme_payment_sub_type,omitempty"`
	SchemePaymentType string `json:"scheme_payment_type,omitempty"`
	EndToEndReference string `json:"end_to_end_reference,omitempty"`
	BeneficiaryParty *PaymentapiBeneficiaryParty `json:"beneficiary_party,omitempty"`
	ChargesInformation *PaymentapiChargersInformation `json:"charges_information,omitempty"`
	Fx *PaymentapiFx `json:"fx,omitempty"`
	DebtorParty *PaymentapiDebtorParty `json:"debtor_party,omitempty"`
	SponsorParty *PaymentapiSponsorParty `json:"sponsor_party,omitempty"`
}
