/*
 * FinTech api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentapiError struct {
	Message string `json:"message,omitempty"`
	Error_ string `json:"error,omitempty"`
	Code int32 `json:"code,omitempty"`
}
