/*
 * FinTech api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PaymentapiSponsorParty struct {
	AccountNumber string `json:"account_number,omitempty"`
	BankId string `json:"bank_id,omitempty"`
	BankIdCode string `json:"bank_id_code,omitempty"`
}
