/*
 * FinTech api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Contact: none@example.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ChargersInformationSenderCharges struct {
	Amount string `json:"amount,omitempty"`
	Currentcy string `json:"currentcy,omitempty"`
}
